# Generated by Django 5.1.1 on 2024-10-08 20:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('O', 'Other'), ('C', 'City/Town/Neighborhood/Village'), ('B', 'Beach / Island'), ('W', 'Waterfall'), ('H', 'Hill / Mountain / Cliff'), ('P', 'Park / Forest / Cave'), ('E', 'Entertainment/Amusement Park'), ('Z', 'Zoo / Wildlife Attraction'), ('M', 'Museum / Art Gallery / Market / Festivals & Parades / Exhibition'), ('H', 'Historical/Heritage Attraction'), ('L', 'Landmark / Unique Built Attraction')], default='O', max_length=1)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='Location')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Visit Date')),
                ('comment', models.TextField(max_length=250)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('image', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
