# Generated by Django 5.1.1 on 2024-10-09 15:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_destination_image_destination_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
