# Generated by Django 5.1.1 on 2024-10-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_destination_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Image URL'),
        ),
    ]
